# Generated by Django 4.2.5 on 2023-09-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailingsettings_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('ERROR', 'ERROR')], default='OK', verbose_name='Attempt status'),
        ),
    ]
