# Generated by Django 4.2.1 on 2023-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('count_of_views', models.IntegerField(verbose_name='Count of views')),
                ('published_date', models.DateTimeField(default=0, verbose_name='Published date/time')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
