# Generated by Django 4.2.1 on 2023-09-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_picture_alter_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_of_views',
            field=models.IntegerField(default=0, verbose_name='Count of views'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published time'),
        ),
    ]
